/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_demo_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_demo_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_demo_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_demo_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_demo_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_demo_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Analyze
         * @description Summarise the window's metrics with the configured AI provider.
         *
         *     The server builds the input itself from aggregates; clients send only the window.
         */
        post: operations["post_analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Analysis */
        Analysis: {
            /** Headline */
            headline: string;
            /** Observations */
            observations: components["schemas"]["Observation"][];
            /** Hypotheses */
            hypotheses: components["schemas"]["Hypothesis"][];
            /** Next Steps */
            next_steps: string[];
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Window Minutes */
            window_minutes?: number | null;
        };
        /**
         * AnalysisResponse
         * @description One shape for both outcomes, so clients handle a single type.
         *
         *     With too little traffic the status is "no_data" and provider, model and analysis are
         *     null; no provider was called.
         */
        AnalysisResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "no_data";
            window: components["schemas"]["AnalysisWindow"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Provider */
            provider: string | null;
            /** Model */
            model: string | null;
            /** Cached */
            cached: boolean;
            analysis: components["schemas"]["Analysis"] | null;
        };
        /** AnalysisWindow */
        AnalysisWindow: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Window Minutes */
            window_minutes: number;
        };
        /** CreateOrderRequest */
        CreateOrderRequest: {
            /** User Id */
            user_id: number;
            /** Items */
            items: components["schemas"]["OrderItem"][];
        };
        /** CreatedOrder */
        CreatedOrder: {
            /** Id */
            id: string;
            /** User Id */
            user_id: number;
            /** Status */
            status: string;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["OrderItem"][];
        };
        /** EndpointMetrics */
        EndpointMetrics: {
            /** Total Requests */
            total_requests: number;
            /** Server Errors */
            server_errors: number;
            /** Client Errors */
            client_errors: number;
            /** Error Rate */
            error_rate: number | null;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
            /** P95 Latency Ms */
            p95_latency_ms: number | null;
            /** Method */
            method: string;
            /** Endpoint */
            endpoint: string;
        };
        /** EndpointTrend */
        EndpointTrend: {
            /** Method */
            method: string;
            /** Endpoint */
            endpoint: string;
            /** Buckets */
            buckets: components["schemas"]["TrendBucket"][];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hypothesis */
        Hypothesis: {
            /** Text */
            text: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium";
        };
        /** LatencyTrend */
        LatencyTrend: {
            /** Overall */
            overall: components["schemas"]["TrendBucket"][];
            /** By Endpoint */
            by_endpoint: components["schemas"]["EndpointTrend"][];
        };
        /** MetricsResponse */
        MetricsResponse: {
            window: components["schemas"]["MetricsWindow"];
            summary: components["schemas"]["Summary"];
            /** Endpoints */
            endpoints: components["schemas"]["EndpointMetrics"][];
            /** Status Codes */
            status_codes: components["schemas"]["StatusCodeCount"][];
            latency_trend: components["schemas"]["LatencyTrend"];
            /** Recent Requests */
            recent_requests: components["schemas"]["RecentRequest"][];
        };
        /** MetricsWindow */
        MetricsWindow: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Window Minutes */
            window_minutes: number;
            /** Bucket Minutes */
            bucket_minutes: number;
        };
        /** Observation */
        Observation: {
            /** Endpoint */
            endpoint: string | null;
            /**
             * Metric
             * @enum {string}
             */
            metric: "total_requests" | "requests_per_minute" | "error_rate" | "client_errors" | "avg_latency_ms" | "p95_latency_ms";
            /** Text */
            text: string;
        };
        /** Order */
        Order: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Total */
            total: number;
            /** Status */
            status: string;
        };
        /** OrderItem */
        OrderItem: {
            /** Product Id */
            product_id: number;
            /** Quantity */
            quantity: number;
        };
        /** OrdersResponse */
        OrdersResponse: {
            /** Orders */
            orders: components["schemas"]["Order"][];
        };
        /** Product */
        Product: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Price */
            price: number;
        };
        /** ProductsResponse */
        ProductsResponse: {
            /** Products */
            products: components["schemas"]["Product"][];
        };
        /** RecentRequest */
        RecentRequest: {
            /** Id */
            id: number;
            /** Method */
            method: string;
            /** Endpoint */
            endpoint: string;
            /** Status Code */
            status_code: number;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Title */
            title: string;
            /** Period */
            period: string;
            /** Rows */
            rows: components["schemas"]["ReportRow"][];
        };
        /** ReportRow */
        ReportRow: {
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Total */
            total: number;
            /** Results */
            results: components["schemas"]["Product"][];
        };
        /** StatusCodeCount */
        StatusCodeCount: {
            /** Status Code */
            status_code: number;
            /** Count */
            count: number;
        };
        /** Summary */
        Summary: {
            /** Total Requests */
            total_requests: number;
            /** Server Errors */
            server_errors: number;
            /** Client Errors */
            client_errors: number;
            /** Error Rate */
            error_rate: number | null;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
            /** P95 Latency Ms */
            p95_latency_ms: number | null;
            /** Requests Per Minute */
            requests_per_minute: number;
        };
        /** TrendBucket */
        TrendBucket: {
            /** Total Requests */
            total_requests: number;
            /** Server Errors */
            server_errors: number;
            /** Client Errors */
            client_errors: number;
            /** Error Rate */
            error_rate: number | null;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
            /** P95 Latency Ms */
            p95_latency_ms: number | null;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** User */
        User: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** UsersResponse */
        UsersResponse: {
            /** Users */
            users: components["schemas"]["User"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_users_demo_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersResponse"];
                };
            };
            /** @description The server failed to process the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The service is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_products_demo_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductsResponse"];
                };
            };
            /** @description The server failed to process the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_orders_demo_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersResponse"];
                };
            };
            /** @description The server failed to process the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The service is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_order_demo_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedOrder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The server failed to process the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The service is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_demo_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The service is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An upstream service took too long to respond. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_report_demo_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description The server failed to process the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An upstream service took too long to respond. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_metrics_metrics_get: {
        parameters: {
            query?: {
                /** @description Window length; defaults to METRICS_WINDOW_MINUTES. */
                window_minutes?: number | null;
                bucket_minutes?: number;
                recent_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The service is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many analyses right now; try again later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The AI provider could not produce an analysis; try again. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI analysis is not configured on this server. Also returned when the database is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
